export const userConstants = {
    USER_LOGIN: "USER_LOGIN",
    USER_LOGOUT: "USER_LOGOUT",
    USER_UPDATE_ALBUM: "USER_UPDATE_ALBUM",
    USER_UPDATE_ONE_ALBUM: "USER_UPDATE_ONE_ALBUM",
    USER_UNSHARE_ALBUM_WITH_ME: "USER_UNSHARE_ALBUM_WITH_ME",
    USER_UNSHARE_IMAGE_WITH_ME: "USER_UNSHARE_IMAGE_WITH_ME",
    USER_UPDATE_ALBUM_AFTER_EDIT: "USER_UPDATE_ALBUM_AFTER_EDIT",
    USER_UPDATE_ALBUM_AFTER_MOVE: "USER_UPDATE_ALBUM_AFTER_MOVE",
    USER_UPDATE_AVATAR: "USER_UPDATE_AVATAR",
    USER_UPDATE_NAME_USER: "USER_UPDATE_NAME_USER",
    USER_UPDATE_IMAGE_AFTER_DELETE: "USER_UPDATE_IMAGE_AFTER_DELETE",
    CHANGE_DARK_MODE: "CHANGE_DARK_MODE"
}